[tool.poetry]
name = "fittrackee"
version = "0.4.7"
description = "Self-hosted outdoor workout/activity tracker"
authors = ["SamR1"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/SamR1/FitTrackee"
documentation = "https://samr1.github.io/FitTrackee"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: JavaScript"
]
exclude = ["fittrackee/tests"]

[tool.poetry.dependencies]
python = "^3.7"
dramatiq = {extras = ["redis"], version = "^1.10.0"}
flask = "^2.0"
flask-bcrypt = "^0.7.1"
flask-dramatiq = "^0.6.0"
flask-migrate = "^3.0"
gpxpy = "=1.3.4"
gunicorn = "^20.1"
humanize = "^3.5.0"
psycopg2-binary = "^2.8"
pycryptodome = "^3.9.9"
pyjwt = "^2.1"
python-forecastio = "^1.4"
pytz = "^2021.1"
shortuuid = "^1.0.1"
staticmap = "^0.5.4"
tqdm = "^4.60"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
freezegun = "^1.1"
mypy = "^0.812"
pyopenssl = "^20.0"
pytest = "^6.2"
pytest-black = "^0.3.12"
pytest-cov = "^2.12"
pytest-flake8 = "^1.0"
pytest-isort = "^2.0"
pytest-runner = "^5.3"
pytest-selenium = "^2.0.1"
recommonmark = "^0.7"
sphinx = "<4.0"
sphinx-bootstrap-theme = "^0.7.1"
sphinxcontrib-httpdomain = "^1.7"

[tool.poetry.scripts]
fittrackee = 'fittrackee.__main__:main'
fittrackee_init_data = 'fittrackee.__main__:init_data'
fittrackee_upgrade_db = 'fittrackee.__main__:upgrade_db'
fittrackee_worker = 'fittrackee.__main__:dramatiq_worker'

[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ["py37", "py38"]
include = ".py$"
exclude = "migrations"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
